import { useState } from "react"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { IconInfo } from "@/components/icons"

export function AboutDialog({ lastUpdated }) {
  const [open, setOpen] = useState(false)

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="icon" aria-label="About WatchTonight" title="About">
          <IconInfo className="h-4 w-4" />
        </Button>
      </DialogTrigger>

      <DialogContent className="sm:max-w-lg max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-lg font-bold">About WatchTonight</DialogTitle>
        </DialogHeader>

        <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">

          {/* Origin story */}
          <section className="space-y-3">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-foreground/60">The problem</h3>
            <p>
              I came across a post on Instagram claiming that{" "}
              <span className="italic text-foreground/80">
                "90% of couples spend more time navigating algorithms than actually watching anything"
              </span>
              {" "}— dubbing it the <span className="text-foreground/80 font-medium">streaming struggle</span>.
              I&apos;m honestly not sure if the statistic was real, but it didn&apos;t matter.
              It described my evenings perfectly.
            </p>
            <p>
              Me and my partner would open Netflix, scroll for twenty minutes, open another app, scroll some more, and
              eventually give up and go to bed. We weren&apos;t spending evenings watching movies —
              we were spending them <em>choosing</em> movies.
            </p>
          </section>

          <div className="border-t border-border/40" />

          {/* What I built */}
          <section className="space-y-3">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-foreground/60">What I built</h3>
            <p>
              I made WatchTonight for ourselves, first. A single curated list of movies and TV seasons
              that are <span className="text-foreground/80 font-medium">recently released to stream at home</span> and
              actually worth watching — ranked by what critics thought, not by what an algorithm is trying to sell you.
            </p>
            <p>
              If you have the same problem, hopefully this helps.
            </p>
          </section>

          <div className="border-t border-border/40" />

          {/* How it works */}
          <section className="space-y-3">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-foreground/60">How it works</h3>
            <p>
              Each item carries a composite score (0–10) aggregated from four sources:
              TMDB vote average, IMDb rating weighted by vote count, Rotten Tomatoes %, and Metacritic score.
              Google Gemini then blends that critical consensus with social popularity signals — trending
              searches, watchlist activity — to shape the final order.
            </p>
            <p>
              Because not every night calls for a masterpiece. Sometimes you just want a fun,
              no-brainer popcorn movie — and the ranking respects that by not burying crowd-pleasers
              behind prestige films.
            </p>
            <p>
              The one-line descriptions are also generated by Gemini so you get a quick flavour
              without reading a full synopsis.
            </p>
            <p>
              No accounts, no tracking, no personalization. The same honest list for everyone.
            </p>
          </section>

          <div className="border-t border-border/40" />

          {/* Data sources */}
          <section className="space-y-2">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-foreground/60">Data sources</h3>
            <ul className="space-y-1.5">
              <li className="flex items-start gap-2">
                <span className="mt-0.5 shrink-0 text-primary/60">·</span>
                <span><span className="text-foreground/80 font-medium">TMDB</span> — metadata, posters, streaming availability</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-0.5 shrink-0 text-primary/60">·</span>
                <span><span className="text-foreground/80 font-medium">OMDb</span> — IMDb, Rotten Tomatoes, and Metacritic ratings</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-0.5 shrink-0 text-primary/60">·</span>
                <span><span className="text-foreground/80 font-medium">Google Gemini</span> — final ranking and one-line descriptions</span>
              </li>
            </ul>
            <p className="pt-1 text-xs text-muted-foreground/60">
              Data is refreshed daily.{lastUpdated ? (
                <> Last updated: <span className="tabular-nums">{new Date(lastUpdated).toLocaleDateString(undefined, { day: "2-digit", month: "short", year: "numeric" })}</span>.</>
              ) : null}
            </p>
          </section>

        </div>
      </DialogContent>
    </Dialog>
  )
}
